name: PictureParticles
main: com.esophose.pictureparticles.PictureParticles
version: 1.0
api-version: 1.13
description: Make pictures out of particles!
author: Esophose
website: https://dev.bukkit.org/projects/pictureparticles
commands:
    pip:
        description: The main PictureParticles command.
